- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_cask_packages_packages:
      - atom
      # - calibre
      - firefox
      - google-chrome
      # - grandperspective
      # - hipchat
      - iterm2
      - java
      - keepassx
      # - kindle
      - mysqlworkbench
      - onepassword
      - skype
      # - spark
      - vagrant
      - virtualbox
      # - zeroxed
  roles:
    - hnakamur.homebrew-cask-packages
